package browseragent

import (
	"embed"
	"encoding/json"
	"fmt"
	"io/fs"
	"os"
	"path/filepath"
	"strings"
)

// embeddedExtension is the staged MV3 tree under embedded/extension/.
// Git tracks only placeholder.txt; full trees are generated by
// script/browser-agent/bundle (or install) and gitignored. Incomplete embeds
// hydrate at runtime from release assets (docs/assets-hydrate.md).
//
//go:embed embedded/extension/**
var embeddedExtension embed.FS

const embeddedExtensionRoot = "embedded/extension"

// embeddedFirefoxExtension is the Firefox MV3 temporary-add-on package.
// Tracked under embedded/extension-firefox/ (P1 shell; not gitignored like Chrome).
//
//go:embed embedded/extension-firefox/**
var embeddedFirefoxExtension embed.FS

const embeddedFirefoxExtensionRoot = "embedded/extension-firefox"

// embeddedFirefoxXPI holds the signed AMO .xpi (browser-agent.xpi) plus optional
// VERSION.txt. Produced by script/browser-agent/firefox/sign and staged by
// script/browser-agent/install. Git tracks placeholder.txt only; fat local
// builds stage browser-agent.xpi (see StageFirefoxXPIEmbed).
//
//go:embed embedded/firefox-xpi/**
var embeddedFirefoxXPI embed.FS

const embeddedFirefoxXPIRoot = "embedded/firefox-xpi"

// embeddedSessionPage is the staged session-page SPA under embedded/session-page/.
// Same placeholder / bundle / hydrate rules as the extension embed.
//
//go:embed embedded/session-page/**
var embeddedSessionPage embed.FS

const embeddedSessionPageRoot = "embedded/session-page"

// SessionPageFS returns the embedded session-page asset tree.
// Paths are rooted under "embedded/session-page/" (index.html, assets/…).
func SessionPageFS() fs.FS {
	return embeddedSessionPage
}

// FormatSessionBootJSON returns boot config JSON for the session SPA:
// session_id, product=browser-agent, control_port=43761 (chrome default).
func FormatSessionBootJSON(sessionID string) string {
	return FormatSessionBootJSONWithBrowser(sessionID, "chrome")
}

// FormatSessionBootJSONWithBrowser returns boot config JSON including the
// operator browser ("chrome" or "firefox") so the SPA can pick install UX.
func FormatSessionBootJSONWithBrowser(sessionID, browser string) string {
	return FormatSessionBootJSONWithBrowserAndExtID(sessionID, browser, "")
}

// FormatSessionBootJSONWithBrowserAndExtID includes optional chrome extension_id
// for session-page externally_connectable register (cold-start fallback).
func FormatSessionBootJSONWithBrowserAndExtID(sessionID, browser, extensionID string) string {
	b := strings.ToLower(strings.TrimSpace(browser))
	if b != "firefox" {
		b = "chrome"
	}
	m := map[string]any{
		"session_id":   sessionID,
		"product":      ProductName,
		"control_port": 43761,
		"browser":      b,
	}
	if id := strings.TrimSpace(extensionID); id != "" {
		m["extension_id"] = id
	}
	raw, err := json.Marshal(m)
	if err != nil {
		// Unreachable for string/int map values; keep a stable fallback.
		return fmt.Sprintf(`{"session_id":%q,"product":%q,"control_port":43761,"browser":%q}`, sessionID, ProductName, b)
	}
	return string(raw)
}

// readEmbeddedSessionIndex loads index.html (or session-page.html) from the embed.
func readEmbeddedSessionIndex() (string, error) {
	candidates := []string{
		embeddedSessionPageRoot + "/index.html",
		embeddedSessionPageRoot + "/session-page.html",
		"index.html",
		"session-page.html",
	}
	var last error
	for _, c := range candidates {
		data, err := embeddedSessionPage.ReadFile(c)
		if err != nil {
			last = err
			continue
		}
		return string(data), nil
	}
	if last == nil {
		last = fmt.Errorf("no session-page index in embed")
	}
	return "", last
}

// ExtractEmbeddedExtension writes the embedded MV3 package under
// {baseDir}/extension/{version}/ and returns the absolute install path and
// version string from manifest.json. Idempotent for the same version.
func ExtractEmbeddedExtension(baseDir string) (installPath, version string, err error) {
	return extractEmbeddedExtensionUnder(baseDir, "extension")
}

// extractEmbeddedExtensionDirect writes the embedded MV3 package under
// {parentDir}/{version}/ (no intermediate subdir). Used by managed Chrome sync.
func extractEmbeddedExtensionDirect(parentDir string) (installPath, version string, err error) {
	return extractEmbeddedExtensionUnder(parentDir, "")
}

func extractEmbeddedExtensionUnder(baseDir, intermediateDir string) (installPath, version string, err error) {
	if strings.TrimSpace(baseDir) == "" {
		return "", "", fmt.Errorf("baseDir is required")
	}
	absBase, err := filepath.Abs(baseDir)
	if err != nil {
		return "", "", fmt.Errorf("resolve baseDir: %w", err)
	}

	maniBytes, err := embeddedExtension.ReadFile(embeddedExtensionRoot + "/manifest.json")
	if err != nil {
		return "", "", fmt.Errorf("read embedded manifest.json: %w", err)
	}
	var mani struct {
		Version string `json:"version"`
	}
	if err := json.Unmarshal(maniBytes, &mani); err != nil {
		return "", "", fmt.Errorf("parse embedded manifest.json: %w", err)
	}
	version = strings.TrimSpace(mani.Version)
	if version == "" {
		return "", "", fmt.Errorf("embedded manifest.json has empty version")
	}

	dest := filepath.Join(absBase, version)
	if strings.TrimSpace(intermediateDir) != "" {
		dest = filepath.Join(absBase, intermediateDir, version)
	}
	if err := os.MkdirAll(dest, 0o755); err != nil {
		return "", "", fmt.Errorf("create extract dir: %w", err)
	}

	err = fs.WalkDir(embeddedExtension, embeddedExtensionRoot, func(path string, d fs.DirEntry, walkErr error) error {
		if walkErr != nil {
			return walkErr
		}
		rel, err := filepath.Rel(embeddedExtensionRoot, path)
		if err != nil {
			return err
		}
		if rel == "." {
			return nil
		}
		rel = filepath.FromSlash(rel)
		target := filepath.Join(dest, rel)
		if d.IsDir() {
			return os.MkdirAll(target, 0o755)
		}
		data, err := embeddedExtension.ReadFile(path)
		if err != nil {
			return fmt.Errorf("read embedded %s: %w", path, err)
		}
		if err := os.MkdirAll(filepath.Dir(target), 0o755); err != nil {
			return err
		}
		return os.WriteFile(target, data, 0o644)
	})
	if err != nil {
		return "", "", fmt.Errorf("extract embedded extension: %w", err)
	}

	absDest, err := filepath.Abs(dest)
	if err != nil {
		return "", "", err
	}
	// Ensure SW-loadable identity file exists after extract (hash excludes itself).
	if _, err := EnsureExtensionBundleSum(absDest, version); err != nil {
		return "", "", fmt.Errorf("ensure bundle-sum.js: %w", err)
	}
	return absDest, version, nil
}

// InstallChromeExtension / InstallChromeExtensionWithHome / install body live in
// install_chrome.go (optional UI Load unpacked via computer-use/macos/chrome).

// BuildChromeArgs returns Chrome argv (without the binary name) for a
// best-effort launch: new window, load-extension, session URL.
// Does not include --user-data-dir (uses the default profile).
func BuildChromeArgs(sessionURL, extensionPath string) []string {
	args := []string{"--new-window"}
	if strings.TrimSpace(extensionPath) != "" {
		args = append(args, "--load-extension="+extensionPath)
	}
	if strings.TrimSpace(sessionURL) != "" {
		args = append(args, sessionURL)
	}
	return args
}

// BuildChromeLaunchArgs is an alias of BuildChromeArgs (browser-trace naming).
func BuildChromeLaunchArgs(sessionURL, extensionPath string) []string {
	return BuildChromeArgs(sessionURL, extensionPath)
}
